# PostgreSQL. Versions 9.3 and up are supported.

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketplace_api_development

test:
  <<: *default
  database: marketplace_api_test

production:
  <<: *default
  database: marketplace_api_production
  username: marketplace_api
  password: <%= ENV["MARKETPLACE_API_DATABASE_PASSWORD"] %>
